name: booboo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1
  logger: ^2.0.2
  riverpod_annotation: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
